networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.

  moodle:
    # image: bitnami/moodle:4.5
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - EXTRA_LOCALES=da_DK.UTF-8 UTF-8
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb  
      - MOODLE_DATABASE_NAME=db
      - MOODLE_DATABASE_USER=db
      - MOODLE_DATABASE_PASSWORD=db
      
      - MOODLE_SITE_NAME=ITK learning

      - MOODLE_SMTP_HOST=mail
      - MOODLE_SMTP_PORT=1025
  
      - "MOODLE_HOST=${COMPOSE_DOMAIN}"
      - MOODLE_REVERSEPROXY=false
      - MOODLE_SSLPROXY=false
    volumes:
      - '.docker/data/moodle:/bitnami/moodle'
      - '.docker/data/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - moodle
    ports:
      - '8080'
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - .:/app
    environment:
      NGINX_WEB_ROOT: /app
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 5M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  mail:
    image: axllent/mailpit
    networks:
      - app
      - frontend
    ports:
      - "1025"
      - "8025"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}mail.rule=Host(`mail-${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}mail.loadbalancer.server.port=8025"
