version: '3'

dotenv: [".task.env", ".env"]

vars:
  DOCKER_COMPOSE: '{{ .TASK_DOCKER_COMPOSE | default "docker compose" }}'
  # https://taskfile.dev/reference/templating/
  BASE_URL: '{{.TASK_BASE_URL | default .COMPOSE_SERVER_DOMAIN | default .COMPOSE_DOMAIN | default ""}}'

  MOODLE_SCRIPTS_DIR: '/bitnami/moodle/admin/cli'

tasks:
  compose:
    desc: "Run `docker compose` command. Example: task compose -- up --detach"
    cmds:
      - '{{ .DOCKER_COMPOSE }} {{ .CLI_ARGS }}'

  compose-exec:
    desc: "Run `docker compose exec` command handling content on stdin. Example: task compose-exec -- phpfpm php -v"
    cmds:
      # Check if we have content on stdin (cf.
      # https://unix.stackexchange.com/questions/762992/bash-check-if-the-standard-input-contains-anything)
      - if [[ ! -t 0 ]]; then task compose -- exec --no-TTY {{ .CLI_ARGS }}; else task compose -- exec {{ .CLI_ARGS }}; fi
    silent: true

  exec-moodle-php:
    desc: "Run a php command within the moodle container"
    cmds:
      - '{{ .DOCKER_COMPOSE }} exec moodle php {{ .CLI_ARGS }}'

  composer:
    desc: "Run composer command. Example: task composer -- install"
    cmds:
      - task compose-exec -- phpfpm composer {{ .CLI_ARGS }}
    silent: true

  start:
    desc: "Start docker compose stuff and install composer stuff"
    cmds:
      - task compose -- pull
      - task compose -- up --detach --remove-orphans --wait
      - git clone git@github.com:itk-dev/itk-moodle.git custom
    silent: true

  site-url:
    desc: "Show site URL"
    cmds:
      - echo {{.URL}}
    vars:
      URL:
        # Compute base URL if not set.
        sh: if [ ! -z "{{.BASE_URL}}" ]; then echo "https://{{.BASE_URL}}"; else echo "http://$(task compose -- port nginx 8080)"; fi
    silent: true

  moodle-script-list:
    desc: "Show available moodle scripts"
    cmds:
      - task compose-exec -- moodle ls -l {{.MOODLE_SCRIPTS_DIR}}

  moodle-script-show:
    desc: "Output a script using cat"
    cmds:
      - task compose-exec -- moodle cat {{.MOODLE_SCRIPTS_DIR}}/{{ .CLI_ARGS }}
    preconditions:
      - sh: "[ {{.CLI_ARGS}} ]"
        msg: "Script name missing"

  moodle-script-run:
    desc: "Run a moodle script within the moodle container"
    cmds:
      - task exec-moodle-php -- {{.MOODLE_SCRIPTS_DIR}}/{{ .CLI_ARGS }}
    preconditions:
      - sh: "[ {{.CLI_ARGS}} ]"
        msg: "Script name missing"